name: Add files to repo

on:
  workflow_dispatch:  # allows manual triggering

jobs:
  dwld-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v6

      - name: delete old bin
        run: |
          rm -f draw.bin white.bin black.bin  

      - name: Download and rename
        run: |
          mkdir -p book
          curl -L -o books/draw.bin https://raw.githubusercontent.com/TheXdOneHimSelf/Polygot/main/draw.bin
          curl -L -o books/white.bin https://raw.githubusercontent.com/TheXdOneHimSelf/Polygot/main/white.bin
          curl -L -o books/black.bin https://raw.githubusercontent.com/TheXdOneHimSelf/Polygot/main/black.bin
          
      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "Commited the file successfully" || echo "Failed to commit the file"
          git push
